version: "3.7"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=dpg-cvh3p81svqrc73b53nfg-a.frankfurt-postgres.render.com
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_database_postgresql
      - DB_POSTGRESDB_USER=n8n_database_postgresql_user
      - DB_POSTGRESDB_PASSWORD=QHUx0iL3fNPMOsTpFwLSQ3eQW3JD2uAl
      - DB_POSTGRESDB_SSL=true
      - DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=QHUx0iL3fNPMOsTpFwLSQ3eQW3JD2uAl
      - ENCRYPTION_KEY=QHUx0iL3fNPMOsTpFwLSQ3eQW3JD2uAl
      - N8N_HOST=ezonline-n8n-webservice.onrender.com
      - N8N_PORT=5678
      - WEBHOOK_URL=https://ezonline-n8n-webservice.onrender.com
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - N8N_LOG_LEVEL=info
      - N8N_JWT_SECRET=3c8ff2d1be1946d998d823bb17335c8c
      - TELEGRAM_BOT_TOKEN=7574502882:AAGVR4EP7Vx5NuQDd7y1TxGZgpo27Yd2es8
      - SERPAPI_KEY=0888c4b51f0d626130b9ef5aa12ffabc98b414e7
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
