services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "443:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=dpg-...
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=...
      - DB_POSTGRESDB_USER=...
      - DB_POSTGRESDB_PASSWORD=...
      - DB_POSTGRESDB_SSL=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=TakeAction4Result!
      - WEBHOOK_URL=https://ezo-n8n.onrender.com
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - TZ=Europe/Amsterdam
      - N8N_ENCRYPTION_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGRhN2MyOS05MTIwLTRlNmItYmRhMy1lMmYwNGUwYzJhYTYiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzQxMDEwNzc5fQ.FZpCmegjXuTfk17hUbURxjw-ERmZp3zsUlaR8SrDdHA
    volumes:
      - .n8n:/home/node/.n8n
